"""initial migration

Revision ID: 816a60009570
Revises:
Create Date: 2026-03-13 21:36:40.333412

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "816a60009570"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("telephone", sa.String(), nullable=False),
        sa.Column("concurrent_logins", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_table(
        "schedule_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("schedule_item_type", sa.String(), nullable=True),
        sa.Column("parent_category", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_item")),
    )
    op.create_table(
        "fee_guides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "province_code",
            sa.Enum(
                "AB",
                "BC",
                "MB",
                "NB",
                "NF",
                "NS",
                "NT",
                "NU",
                "ON",
                "PE",
                "QC",
                "SK",
                "YT",
                name="provincecode",
            ),
            nullable=False,
        ),
        sa.Column(
            "specialty_code",
            sa.Enum(
                "GEN",
                "PUB",
                "ENDO",
                "ORTHO",
                "PED",
                "PERIO",
                "PROS",
                "OMFP",
                "OMFR",
                "OMFS",
                name="specialty",
            ),
            nullable=False,
        ),
        sa.Column("year_effective", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_guides")),
    )
    op.create_table(
        "fee_guide_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fee_min_cents", sa.Integer(), nullable=False),
        sa.Column("fee_max_cents", sa.Integer(), nullable=False),
        sa.Column("fee_strategy", sa.String(), nullable=False),
        sa.Column("has_L_flag", sa.Boolean(), nullable=True),
        sa.Column("has_E_flag", sa.Boolean(), nullable=True),
        sa.Column("has_PS_flag", sa.Boolean(), nullable=True),
        sa.Column("fee_guide_id", sa.Integer(), nullable=False),
        sa.Column("schedule_item_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["schedule_item_id"],
            ["schedule_item.id"],
            name=op.f("fk_fee_guide_item_schedule_item_id_schedule_item"),
        ),
        sa.ForeignKeyConstraint(
            ["fee_guide_id"],
            ["fee_guides.id"],
            name=op.f("fk_fee_guide_item_fee_guide_id_fee_guides"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_guide_item")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("_password_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("name_first", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("name_last", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.create_unique_constraint(
            "users_email_key", ["email"], postgresql_nulls_not_distinct=False
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(),
            type_=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        )
        batch_op.drop_column("username")

    op.create_table(
        "products",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('products_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("origin_country", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("price_cents", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("sale_unit", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("package_quantity", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("image_filename", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="products_pkey"),
        sa.UniqueConstraint(
            "name",
            name="products_name_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "order_products",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("price_cents", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name="fk_order_products_order_id_orders"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name="fk_order_products_product_id_products",
        ),
        sa.PrimaryKeyConstraint("id", name="order_products_pkey"),
        sa.UniqueConstraint(
            "order_id",
            "product_id",
            name="_order_product_uc",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("address_line_1", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("address_line_2", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("province_code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("postal_code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("product_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "final_total_cents", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_orders_user_id_users"
        ),
        sa.PrimaryKeyConstraint("id", name="orders_pkey"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            "one_open_order_per_user",
            ["user_id"],
            unique=True,
            postgresql_where="((status)::text = 'open'::text)",
        )

    op.drop_table("fee_guide_item")
    op.drop_table("fee_guides")
    op.drop_table("schedule_item")
    op.drop_table("clients")
    # ### end Alembic commands ###
