"""Add province specificity and category tracking fields

Revision ID: 9d43c9af73c5
Revises: d70ce40c00a3
Create Date: 2026-03-18 00:55:38.580033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d43c9af73c5'
down_revision = 'd70ce40c00a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('parent_category', sa.String(), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=True),
    sa.Column('provinces', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_items'))
    )
    op.create_table('fee_guide_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_min_cents', sa.Integer(), nullable=False),
    sa.Column('fee_max_cents', sa.Integer(), nullable=False),
    sa.Column('fee_strategy', sa.String(), nullable=False),
    sa.Column('has_L_flag', sa.Boolean(), nullable=True),
    sa.Column('has_E_flag', sa.Boolean(), nullable=True),
    sa.Column('has_PS_flag', sa.Boolean(), nullable=True),
    sa.Column('is_province_specific', sa.Boolean(), nullable=True),
    sa.Column('fee_guide_id', sa.Integer(), nullable=False),
    sa.Column('schedule_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fee_guide_id'], ['fee_guides.id'], name=op.f('fk_fee_guide_items_fee_guide_id_fee_guides')),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['schedule_items.id'], name=op.f('fk_fee_guide_items_schedule_item_id_schedule_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_guide_items'))
    )
    op.drop_table('fee_guide_item')
    op.drop_table('schedule_item')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('concurrent_logins')

    with op.batch_alter_table('fee_guides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_fee_guides_account_id_accounts'), 'accounts', ['account_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_users_account_id_accounts'), 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_account_id_accounts'), type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('fee_guides', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_fee_guides_account_id_accounts'), type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concurrent_logins', sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('schedule_item',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('schedule_item_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('schedule_item_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_schedule_item'),
    postgresql_ignore_search_path=False
    )
    op.create_table('fee_guide_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fee_min_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fee_max_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fee_strategy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('has_L_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_E_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_PS_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fee_guide_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schedule_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fee_guide_id'], ['fee_guides.id'], name='fk_fee_guide_item_fee_guide_id_fee_guides'),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['schedule_item.id'], name='fk_fee_guide_item_schedule_item_id_schedule_item'),
    sa.PrimaryKeyConstraint('id', name='pk_fee_guide_item')
    )
    op.drop_table('fee_guide_items')
    op.drop_table('schedule_items')
    # ### end Alembic commands ###
