"""Add updated_by to FeeGuideItem

Revision ID: e133db9ef708
Revises: 9d43c9af73c5
Create Date: 2026-03-18 04:59:13.159333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e133db9ef708'
down_revision = '9d43c9af73c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_guide_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_guide_items', schema=None) as batch_op:
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###
