"""add parent_category to FeeGuideItem

Revision ID: f4967fc3e91f
Revises: e133db9ef708
Create Date: 2026-03-18 08:54:43.877032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4967fc3e91f'
down_revision = 'e133db9ef708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_guide_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_guide_items', schema=None) as batch_op:
        batch_op.drop_column('parent_category')

    # ### end Alembic commands ###
